Vagrant.configure(2) do |config|
  config.vm.box = "ogarcia/archlinux-201510-x64"

  config.vm.box_check_update = false

  config.vm.synced_folder "../../", "/mnt/knapsen/"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
 
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  config.vm.provision :shell, path: "bootstrap.sh"

end
