var MAIN_WIDTH = 900;

var MAIN_HEIGHT = 700;

var TEXT_RECT_DISTANCE_WIDTH = 15;

var TEXT_RECT_DISTANCE_HEIGHT = 10;

var NAME_DISTANCE = 10;

var SCORE_TABLE_DISTANCE = 10;

var ANIMATION_TIME = 200; //2000

var DECK_DISTANCE = 50;

var NAME_CARDSGROUP_DISTANCE = 10;

var DECK_TRUMP_DISTANCE = 20;

var INVALID_CARD_ID = -1;
